version: '3.8'

services:
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  client_reactjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_reactjs
    ports:
      - "3000:3000"
    depends_on:
      - backend

      
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb



  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client_reactjs

volumes:
  mongodb_data:
