name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push mongodb Docker image
      run: |
        docker build ./zettour/bookit-mongodb --file Dockerfile.bookit-mongodb --tag zettour/bookit-mongodb:$(date +%s)
        docker push zettour/bookit-mongodb:$(date +%s)
        
    - name: Build and push backend Docker image
      run: |
        docker build ./zettour/bookit-backend --file Dockerfile.bookit-backend --tag zettour/bookit-backend:$(date +%s)
        docker push zettour/bookit-backend:$(date +%s)

    - name: Build and push client_reactjs Docker image
      run: |
        docker build ./zettour/bookit-client_reactjs --file Dockerfile.bookit-client_reactjs --tag zettour/bookit-client_reactjs:$(date +%s)
        docker push zettour/bookit-client_reactjs:$(date +%s)

    - name: Build and push nginx Docker image
      run: |
        docker build ./zettour/bookit-nginx --file Dockerfile.bookit-nginx --tag zettour/bookit-nginx:$(date +%s)
        docker push zettour/bookit-nginx:$(date +%s)
