name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    services:
  
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # - name: Build and push client_reactjs Docker image
    #   run: |
    #     SHA=$(git rev-parse HEAD)
    #     docker build . --file Dockerfile.client_reactjs --tag zettour/bookit-client_reactjs:$SHA
    #     docker push zettour/bookit-client_reactjs:$SHA

    # - name: Build and push backend Docker image
    #   run: |
    #     SHA=$(git rev-parse HEAD)
    #     docker build ./backend --file Dockerfile.backend --tag zettour/bookit-backend:$SHA
    #     docker push zettour/bookit-backend:$SHA

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    - name: Run tests
      run: |
        docker-compose exec client_reactjs npm test

    - name: Teardown
      run: |
        docker-compose down
