name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    

    # - name: Build and push client_reactjs Docker image
    #   run: |
    #     SHA=$(git rev-parse HEAD)
    #     docker build . --file Dockerfile.client_reactjs --tag zettour/bookit-client_reactjs:$SHA
    #     docker push zettour/bookit-client_reactjs:$SHA

    # - name: Build and push backend Docker image
    #   run: |
    #     SHA=$(git rev-parse HEAD)
    #     docker build ./backend --file Dockerfile.backend --tag zettour/bookit-backend:$SHA
    #     docker push zettour/bookit-backend:$SHA

    # - name: Build and push Docker images
    #   run: |
    #     docker-compose -f docker-compose.yml build
    #     docker-compose -f docker-compose.yml up -d

    # - name: Teardown
    #   run: |
    #     docker-compose down

  # deploy test
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Configure Docker CLI
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Pull Docker image
        run: 
          docker image pull zettour/bookit-nginx:latest
          docker image pull zettour/bookit-client_reactjs:latest
          docker image pull zettour/bookit-backend:latest
          docker image pull zettour/bookit-mongo::latest

      - name: Run dockercompose backend
        run:
          cd bookit-backend
          docker-compose -f docker-compose.yml up -d
      - name: Run dockercompose client
        run:
          cd bookit-client_reactjs
          docker-compose -f docker-compose.yml up -d

      
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm -v $(pwd)/_site:/app/_site bookit npm run deploy
