name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push mongodb Docker image
      run: |
        SHA=$(git rev-parse HEAD)
        docker build ./zettour/bookit-mongo --file Dockerfile.zettour/bookit-mongo --tag zettour/bookit-mongo:$SHA
        docker push zettour/bookit-mongodb:$SHA
        
    - name: Build and push backend Docker image
      run: |
        SHA=$(git rev-parse HEAD)
        docker build ./zettour/bookit-backend --file Dockerfile.zettour/bookit-backend --tag zettour/bookit-backend:$SHA
        docker push zettour/bookit-backend:$SHA

    - name: Build and push client_reactjs Docker image
      run: |
        SHA=$(git rev-parse HEAD)
        docker build ./zettour/bookit-client_reactjs --file Dockerfile.zettour/bookit-client_reactjs --tag zettour/bookit-client_reactjs:$SHA
        docker push zettour/bookit-client_reactjs:$SHA

    - name: Build and push nginx Docker image
      run: |
        SHA=$(git rev-parse HEAD)
        docker build ./zettour/bookit-nginx --file Dockerfile.zettour/bookit-nginx --tag zettour/bookit-nginx:$SHA
        docker push zettour/bookit-nginx:$SHA
